/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlocacaoRouteImport } from './routes/alocacao'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as PerfilamentoRouteImport } from './routes/perfilamento'
import { Route as RebalanceamentoRouteImport } from './routes/rebalanceamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlocacaoRoute = AlocacaoRouteImport.update({
  id: '/alocacao',
  path: '/alocacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilamentoRoute = PerfilamentoRouteImport.update({
  id: '/perfilamento',
  path: '/perfilamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RebalanceamentoRoute = RebalanceamentoRouteImport.update({
  id: '/rebalanceamento',
  path: '/rebalanceamento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alocacao': typeof AlocacaoRoute
  '/analise': typeof AnaliseRoute
  '/carteira': typeof CarteiraRoute
  '/perfilamento': typeof PerfilamentoRoute
  '/rebalanceamento': typeof RebalanceamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alocacao': typeof AlocacaoRoute
  '/analise': typeof AnaliseRoute
  '/carteira': typeof CarteiraRoute
  '/perfilamento': typeof PerfilamentoRoute
  '/rebalanceamento': typeof RebalanceamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alocacao': typeof AlocacaoRoute
  '/analise': typeof AnaliseRoute
  '/carteira': typeof CarteiraRoute
  '/perfilamento': typeof PerfilamentoRoute
  '/rebalanceamento': typeof RebalanceamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alocacao'
    | '/analise'
    | '/carteira'
    | '/perfilamento'
    | '/rebalanceamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alocacao'
    | '/analise'
    | '/carteira'
    | '/perfilamento'
    | '/rebalanceamento'
  id:
    | '__root__'
    | '/'
    | '/alocacao'
    | '/analise'
    | '/carteira'
    | '/perfilamento'
    | '/rebalanceamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlocacaoRoute: typeof AlocacaoRoute
  AnaliseRoute: typeof AnaliseRoute
  CarteiraRoute: typeof CarteiraRoute
  PerfilamentoRoute: typeof PerfilamentoRoute
  RebalanceamentoRoute: typeof RebalanceamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alocacao': {
      id: '/alocacao'
      path: '/alocacao'
      fullPath: '/alocacao'
      preLoaderRoute: typeof AlocacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfilamento': {
      id: '/perfilamento'
      path: '/perfilamento'
      fullPath: '/perfilamento'
      preLoaderRoute: typeof PerfilamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rebalanceamento': {
      id: '/rebalanceamento'
      path: '/rebalanceamento'
      fullPath: '/rebalanceamento'
      preLoaderRoute: typeof RebalanceamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlocacaoRoute: AlocacaoRoute,
  AnaliseRoute: AnaliseRoute,
  CarteiraRoute: CarteiraRoute,
  PerfilamentoRoute: PerfilamentoRoute,
  RebalanceamentoRoute: RebalanceamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
