/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlocacaoRouteImport } from './routes/alocacao'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as PerfilamentoRouteImport } from './routes/perfilamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlocacaoRoute = AlocacaoRouteImport.update({
  id: '/alocacao',
  path: '/alocacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilamentoRoute = PerfilamentoRouteImport.update({
  id: '/perfilamento',
  path: '/perfilamento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alocacao': typeof AlocacaoRoute
  '/carteira': typeof CarteiraRoute
  '/perfilamento': typeof PerfilamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alocacao': typeof AlocacaoRoute
  '/carteira': typeof CarteiraRoute
  '/perfilamento': typeof PerfilamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alocacao': typeof AlocacaoRoute
  '/carteira': typeof CarteiraRoute
  '/perfilamento': typeof PerfilamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alocacao' | '/carteira' | '/perfilamento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alocacao' | '/carteira' | '/perfilamento'
  id: '__root__' | '/' | '/alocacao' | '/carteira' | '/perfilamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlocacaoRoute: typeof AlocacaoRoute
  CarteiraRoute: typeof CarteiraRoute
  PerfilamentoRoute: typeof PerfilamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alocacao': {
      id: '/alocacao'
      path: '/alocacao'
      fullPath: '/alocacao'
      preLoaderRoute: typeof AlocacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfilamento': {
      id: '/perfilamento'
      path: '/perfilamento'
      fullPath: '/perfilamento'
      preLoaderRoute: typeof PerfilamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlocacaoRoute: AlocacaoRoute,
  CarteiraRoute: CarteiraRoute,
  PerfilamentoRoute: PerfilamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
