// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfafvpsixaotzegvvwkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmYWZ2cHNpeGFvdHplZ3Z2d2t4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMTQzNzYsImV4cCI6MjA3NDY5MDM3Nn0.8Z-PQ5t0cwZssDqf8zE73GnhJgnetmetURFak29Lk4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});